
services:
###> doctrine/doctrine-bundle ###

  database:
    image: mysql
    restart: always

    environment:
      
      # You should definitely change the password in production
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jobit
      MYSQL_USER: jobit
      MYSQL_PASSWORD: jobit
      
    volumes:
      - database_data:/var/lib/mysql
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###
  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      PMA_HOST: database
    ports:
      - 8081:80
    depends_on:
      - database

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
